language: python
python:
  - "3.5"
before_install:
 - sudo apt-get install python3-tk
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 3
cache: pip
install:
  - python3 -mpip install -U matplotlib
script:
  - python3 main.py
